name: Release

on:
  release:
    types: [ published ]

defaults:
  run:
    shell: bash -l {0}

jobs:
  Build:
      name: Build
      permissions:
        statuses: write
        pull-requests: write
      uses: ./.github/workflows/_build.yml
  Deploy:
    name: Deploy
    runs-on: macos-11
    environment: Publishing
    needs: [Build]
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    
    - name: Install cocoapods
      run: gem install cocoapods
      
    - name: Pod repo update
      run: | 
        pod repo update

    - uses: release-drafter/release-drafter@v5
      if: ${{ github.event.inputs.action_tag == 'yes' }}
      with:
        name: v${{ github.event.inputs.tag }}
        tag: ${{ github.event.inputs.tag }}
        version: ${{ github.event.inputs.tag }}
        publish: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Pods - Backpack Common
      run: |
        set -eo pipefail
        pod trunk push Backpack-Common.podspec --allow-warnings --synchronous
        pod repo update
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

    - name: Publish Pods - Backpack UIKit
      run: |
        set -eo pipefail
        pod trunk push Backpack.podspec --allow-warnings --synchronous
        pod repo update
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

    - name: Publish Pods - Backpack SwiftUI
      run: |
        set -eo pipefail
        pod trunk push Backpack-SwiftUI.podspec --allow-warnings --synchronous
        pod repo update
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}