name: release

on:
  release:
    types: [ published ]

defaults:
  run:
    shell: bash -l {0}

jobs:
  Build:
      name: Build
      permissions:
        statuses: write
        pull-requests: write
      uses: ./.github/workflows/_build.yml
      secrets:
        GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
  Deploy-Common:
    name: Release Common to Cocoapods
    runs-on: macos-14
    environment: Publishing
    needs: [Build]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v6
      with:
        ref: main
        persist-credentials: false

    - name: Set up node and ruby
      uses: asdf-vm/actions/install@v4 # Sets ruby and node version via `.tool-versions`

    - name: Bundle Install
      run: bundle install --jobs 4 --retry 3

    - name: Select Xcode 16
      run: sudo xcode-select --switch /Applications/Xcode_16.2.app

    - name: Publish Pods - Backpack Common
      run: |
        set -eo pipefail
        bundle exec pod trunk push Backpack-Common.podspec --allow-warnings --skip-tests --synchronous
        bundle exec pod repo update
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        LIB_VERSION: ${{ github.event.release.tag_name }}

  Deploy-UIKit:
    name: Release UIKit to Cocoapods
    runs-on: macos-14
    environment: Publishing
    needs: [Build]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v6
      with:
        ref: main
        persist-credentials: false

    - name: Set up node and ruby
      uses: asdf-vm/actions/install@v4 # Sets ruby and node version via `.tool-versions`

    - name: Bundle Install
      run: bundle install --jobs 4 --retry 3

    - name: Select Xcode 16
      run: sudo xcode-select --switch /Applications/Xcode_16.2.app

    - name: Publish Pods - Backpack UIKit
      run: |
        set -eo pipefail
        bundle exec pod trunk push Backpack.podspec --allow-warnings --skip-tests --synchronous
        bundle exec pod repo update
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        LIB_VERSION: ${{ github.event.release.tag_name }}

  Deploy-SwiftUI:
    name: Release SwiftUI to Cocoapods
    runs-on: macos-14
    environment: Publishing
    needs: [Build]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v6
      with:
        ref: main
        persist-credentials: false

    - name: Set up node and ruby
      uses: asdf-vm/actions/install@v4 # Sets ruby and node version via `.tool-versions`

    - name: Bundle Install
      run: bundle install --jobs 4 --retry 3

    - name: Select Xcode 16
      run: sudo xcode-select --switch /Applications/Xcode_16.2.app

    - name: Publish Pods - Backpack SwiftUI
      run: |
        set -eo pipefail
        bundle exec pod trunk push Backpack-SwiftUI.podspec --allow-warnings --skip-tests --synchronous
        bundle exec pod repo update
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        LIB_VERSION: ${{ github.event.release.tag_name }}

  Deploy-Docs:
    name: Release Backpack Docs
    runs-on: macos-14
    environment: Publishing
    needs: [Deploy-SwiftUI, Deploy-UIKit, Deploy-Common]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v6
      with:
        ref: main
        persist-credentials: false

    - name: Set up node and ruby
      uses: asdf-vm/actions/install@v4 # Sets ruby and node version via `.tool-versions``

    - name: Bundle Install
      run: bundle install --jobs 4 --retry 3

    - name: Pod Install
      run: bundle exec pod install
      working-directory: Example

    - name: Install sourcekitten
      run: brew install sourcekitten

    - name: Build and verify docs (release)
      if: github.event.release.tag_name != ''
      run: ./scripts/build-docs $RELEASE_VERSION
      env:
        RELEASE_VERSION: ${{ github.event.release.tag_name }}

    - name: Deploy code documentation
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.DEPLOY_TOKEN }}
        publish_dir: docs/
        keep_files: true
        external_repository: backpack/ios
        publish_branch: main

  SupernovaPublish:
    runs-on: ubuntu-22.04
    environment: Publishing
    steps:
      - name: Update Supernova docs
        run: npx @supernovaio/cli publish-documentation --apiKey=${{ secrets.SUPERNOVA_API_KEY }} --designSystemId=${{ secrets.SUPERNOVA_DESIGN_SYSTEM_ID }}
